[package]
name = "foxbox_users"
version = "0.1.0"
authors = ["Fernando Jiménez Moreno <ferjmoreno@gmail.com>"]

[dependencies]
iron = "*"
libc = "*"
router = "*"
rusqlite = "*"
rust-crypto = "*"
unicase = "*"
stainless = { git = "https://github.com/reem/stainless.git", rev = "82392f2e" }
